[package]
name = "rdc"
version = "0.1.0"
authors = ["Enrico Franchi <enrico.franchi@gmail.com>"]

[dependencies]
num = "0.1.42"
num-bigint = "0.1"
bigdecimal = "0.0.11"

[features]
default = []
tracevm = []